### ISSUE TITLE
[CRASH] Incompatible with Better Statistics Screen

### ISSUE THREAD

**Issue by JENOVAAbsolute** [MDLC01/higher-chat-mc#5]
Game crashes upon opening the player inventory.
Crash log:
[crash-2024-07-30_15.20.39-client.txt](https://github.com/user-attachments/files/16432551/crash-2024-07-30_15.20.39-client.txt)

Latest log:
[latest.log](https://github.com/user-attachments/files/16432554/latest.log)

Conflicting mod:
https://modrinth.com/mod/better-stats

**Comment by JENOVAAbsolute** [comment]
After further testing, the issue is caused by Better Statistics Screen. That mod is also causing the same crash with several other mods. I will report this on their issue tracker later.

**Comment by MDLC01** [comment]
I'm closing this issue for now. Feel free to re-open it if you find evidence that Higher Chat is the mod causing the problem.
